<a href="https://colab.research.google.com/github/kushal-0021/user-sentiment-analysis/blob/main/User_sentiment_analysis_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/train.csv')

In [ ]:
df.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [ ]:
# prompt: count the number of 0s and 1s in the label column

zero_count = df['label'].value_counts()[0]
one_count = df['label'].value_counts()[1]
print(f"Number of 0s: {zero_count}")
print(f"Number of 1s: {one_count}")

Number of 0s: 20109
Number of 1s: 1493


In [ ]:
df.isnull().sum()

id       0
label    0
tweet    0
dtype: int64

In [ ]:
df=df.dropna()

In [ ]:
X=df.drop('label',axis=1)
X.shape

(21602, 2)

In [ ]:
y=df['label']
y.shape

(21602,)

In [ ]:
!pip install tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 644.9/644.9 MB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 80.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 112.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 100.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 110.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 16.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 5.3 MB/s eta 0:00:00


In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.19.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
voc_size=5000

In [ ]:
messages= X.copy()

In [ ]:
messages

id                                              tweet
0          1   @user when a father is dysfunctional and is s...
1          2  @user @user thanks for #lyft credit i can't us...
2          3                                bihday your majesty
3          4  #model   i love u take with u all the time in ...
4          5             factsguide: society now    #motivation
...      ...                                                ...
21597  21598  i'm so   today my small #cousin got his first ...
21598  21599  for #rohingya, fear and forced marriages #traf...
21599  21600    birds &amp; bad #piggies #finger family \ #n...
21600  21601  now that #bfestbuzz is winding down, get   for...
21601  21602                             no history of an incid

[21602 rows x 2 columns]

In [ ]:
messages['tweet'][1]

"@user @user thanks for #lyft credit i can't use cause they don't offer wheelchair vans in pdx.    #disapointed #getthanked"

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['tweet'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['user father dysfunct selfish drag kid dysfunct run',
 'user user thank lyft credit use caus offer wheelchair van pdx disapoint getthank',
 'bihday majesti',
 'model love u take u time ur',
 'factsguid societi motiv',
 'huge fan fare big talk leav chao pay disput get allshowandnogo',
 'user camp tomorrow user user user user user user user danni',
 'next school year year exam think school exam hate imagin actorslif revolutionschool girl',
 'love land allin cav champion cleveland clevelandcavali',
 'user user welcom gr',
 'ireland consum price index mom climb previou may blog silver gold forex',
 'selfish orlando standwithorlando pulseshoot orlandoshoot biggerproblem selfish heabreak valu love',
 'get see daddi today day gettingf',
 'user cnn call michigan middl school build wall chant tcot',
 'comment australia opkillingbay seashepherd helpcovedolphin thecov helpcovedolphin',
 'ouch junior angri got junior yugyoem omg',
 'thank paner thank posit',
 'retweet agre',
 'friday smile around

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[1447, 4628, 4432, 2562, 2304, 2833, 4432, 143],
 [1447, 1447, 40, 3739, 1991, 4058, 315, 1701, 171, 2068, 1202, 1011, 1208],
 [4870, 1114],
 [690, 2716, 3170, 4764, 3170, 3718, 4352],
 [4354, 958, 4943],
 [918, 2617, 624, 1171, 265, 664, 2743, 247, 782, 3405, 3582],
 [1447, 384, 1188, 1447, 1447, 1447, 1447, 1447, 1447, 1447, 267],
 [1587, 3290, 972, 972, 539, 638, 3290, 539, 3521, 607, 3492, 1440, 4264],
 [2716, 4440, 3794, 17, 645, 2621, 2163],
 [1447, 1447, 4350, 3439],
 [3812, 3602, 3254, 4323, 1503, 1347, 507, 1612, 4661, 4162, 232, 2664],
 [2562, 775, 1352, 3621, 218, 929, 2562, 3989, 2764, 2716],
 [3405, 3067, 381, 4848, 3278, 2578],
 [1447, 1950, 4715, 2133, 76, 3290, 4112, 217, 1394, 3388],
 [591, 1196, 4233, 2404, 986, 442, 986],
 [1098, 3614, 857, 1882, 3614, 3747, 2180],
 [40, 4843, 40, 763],
 [554, 4291],
 [4168, 2804, 2787, 1931, 162, 1447, 1447, 3226, 2304, 493],
 [1936, 1950, 4905, 2836, 3585],
 [1493,
  493,
  3666,
  3052,
  2557,
  4834,
  3958,
  1373,
  4103,
  1

In [ ]:
onehot_repr[1]

[1447, 1447, 40, 3739, 1991, 4058, 315, 1701, 171, 2068, 1202, 1011, 1208]

In [ ]:
corpus[1]

'user user thank lyft credit use caus offer wheelchair van pdx disapoint getthank'

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[1447 4628 4432 ...    0    0    0]
 [1447 1447   40 ...    0    0    0]
 [4870 1114    0 ...    0    0    0]
 ...
 [ 463 2524 1133 ...    0    0    0]
 [3923 2070 3405 ...    0    0    0]
 [1004 1681    0 ...    0    0    0]]


In [ ]:
embedded_docs[1]

array([1447, 1447,   40, 3739, 1991, 4058,  315, 1701,  171, 2068, 1202,
       1011, 1208,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
model.build(input_shape=(None, sent_length))

In [ ]:
print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
len(embedded_docs),y.shape

(21602, (21602,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((21602, 20), (21602,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
227/227 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - accuracy: 0.9272 - loss: 0.3006 - val_accuracy: 0.9452 - val_loss: 0.1614
Epoch 2/10
227/227 ━━━━━━━━━━━━━━━━━━━━ 5s 23ms/step - accuracy: 0.9662 - loss: 0.1094 - val_accuracy: 0.9494 - val_loss: 0.1677
Epoch 3/10
227/227 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step - accuracy: 0.9790 - loss: 0.0658 - val_accuracy: 0.9509 - val_loss: 0.1699
Epoch 4/10
227/227 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step - accuracy: 0.9868 - loss: 0.0472 - val_accuracy: 0.9422 - val_loss: 0.2172
Epoch 5/10
227/227 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step - accuracy: 0.9894 - loss: 0.0417 - val_accuracy: 0.9314 - val_loss: 0.2460
Epoch 6/10
227/227 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step - accuracy: 0.9929 - loss: 0.0258 - val_accuracy: 0.9438 - val_loss: 0.2514
Epoch 7/10
227/227 ━━━━━━━━━━━━━━━━━━━━ 5s 23ms/step - accuracy: 0.9937 - loss: 0.0229 - val_accuracy: 0.9404 - val_loss: 0.2332
Epoch 8/10
227/227 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step - accuracy: 0.9950 - loss: 0.0237 - val_accu

y_pred=model.predict(X_test)

In [ ]:
y_pred=model.predict(X_test)

223/223 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step


In [ ]:
y_pred=np.where(y_pred > 0.6, 1,0)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[6538,  100],
       [ 304,  187]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.943330060317015

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97      6638
           1       0.65      0.38      0.48       491

    accuracy                           0.94      7129
   macro avg       0.80      0.68      0.73      7129
weighted avg       0.93      0.94      0.94      7129

